theme: jekyll-theme-minimal
title: Monserrat Lopez
author: Monserrat
logo: /photo/1.jpeg
name: Monlo
email: lopezmonserrat.14@gmail.com
description: Análisis de datos e investigación sobre políticas públicas
show_excerpts: false # set to true to show excerpts on the homepage

# generate social links in footer
social_links:
twitter: MonLopez_
github:  Monlo
instagram: monlopez__

