theme: jekyll-theme-minimal
title: Monserrat López
author: Monserrat
logo: /photo/2.png
description: Análisis de datos e investigación sobre políticas públicas
show_excerpts: false # set to true to show excerpts on the homepage


